'use strict';
(function(H){
 const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const key='higaeri.v1.',memoryStorage={};let storageOK=true;
 const storage={get(k){try{return localStorage.getItem(key+k)}catch(e){storageOK=false;return memoryStorage[k]||null}},set(k,v){memoryStorage[k]=v;try{localStorage.setItem(key+k,v);return true}catch(e){storageOK=false;return false}}};
 const fresh=()=>({version:1,map:'home',x:10*32,y:15.3*32,dir:{x:0,y:1},light:true,flags:{},items:[],memories:[],lore:[],chapter:0,seconds:0,checkpoint:{map:'home',x:18.5*32,y:18*32}});
 function validate(raw){if(!raw||raw.version!==1||!H.maps[raw.map])throw Error('このゲームのセーブデータではありません。');const m=H.maps[raw.map];if(!Number.isFinite(raw.x)||!Number.isFinite(raw.y)||raw.x<16||raw.y<16||raw.x>m.w*32-16||raw.y>m.h*32-16)throw Error('セーブ位置が不正です。');if(!raw.flags||typeof raw.flags!=='object'||Array.isArray(raw.flags))throw Error('進行情報が不正です。');const allowedFlags=['letter','bell','stallTalk','mask','chimes','honest','mirror','key','schoolTruth','thread','ritualHint','altar','name'];const flags={};for(const k of allowedFlags){if(raw.flags[k]!==undefined&&typeof raw.flags[k]!=='boolean')throw Error('進行情報が不正です。');if(raw.flags[k])flags[k]=true}const f=flags;if((f.bell&&!f.letter)||(f.mirror&&(!f.bell||!f.mask||!f.chimes))||(f.key&&!f.mirror)||(f.schoolTruth&&!f.key)||(f.thread&&!f.schoolTruth)||(f.altar&&!f.thread))throw Error('物語の進行が不正です。');const arr=(a,table)=>{if(!Array.isArray(a)||a.some(k=>typeof k!=='string'||!Object.hasOwn(table,k)))throw Error('手帳の情報が不正です。');return [...new Set(a)]};const s=fresh();s.map=raw.map;s.x=raw.x;s.y=raw.y;s.flags=flags;s.items=arr(raw.items,H.items);s.memories=arr(raw.memories,H.memories);s.lore=arr(raw.lore,H.lore);if(f.name&&s.memories.length<7)throw Error('記憶の情報が不正です。');s.items=Object.keys(H.items).filter(k=>flags[k]);s.chapter=flags.altar?4:flags.thread?3:flags.mirror?2:flags.bell?1:0;s.seconds=Number.isFinite(raw.seconds)?clamp(raw.seconds,0,1e8):0;s.light=raw.light!==false;if(raw.dir&&Number.isFinite(raw.dir.x)&&Number.isFinite(raw.dir.y)&&Math.hypot(raw.dir.x,raw.dir.y)>.5){const n=Math.hypot(raw.dir.x,raw.dir.y);s.dir={x:raw.dir.x/n,y:raw.dir.y/n}}const cp=raw.checkpoint;if(cp&&H.maps[cp.map]&&Number.isFinite(cp.x)&&Number.isFinite(cp.y)&&cp.x>16&&cp.y>16&&cp.x<H.maps[cp.map].w*32-16&&cp.y<H.maps[cp.map].h*32-16)s.checkpoint={map:cp.map,x:cp.x,y:cp.y};return s}
 class Sound{
 constructor(){this.ctx=null;this.volume=.45;this.nextNote=0;this.stepTime=0;this.heartTime=0}
 init(){if(this.ctx){this.ctx.resume().catch(()=>{});return}try{this.ctx=new(window.AudioContext||window.webkitAudioContext)();const a=this.ctx;this.master=a.createGain();this.master.gain.value=this.volume*.4;this.master.connect(a.destination);this.pad=a.createGain();this.pad.gain.value=.11;this.pad.connect(this.master);[73.42,110.05,146.72].forEach((f,i)=>{const o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=f;g.gain.value=i===0?.36:.15;o.connect(g);g.connect(this.pad);o.start()});const n=a.createBuffer(1,a.sampleRate*3,a.sampleRate);const data=n.getChannelData(0);let prev=0;for(let i=0;i<data.length;i++){prev=(prev+(Math.random()*2-1)*.06)/1.025;data[i]=prev}this.noise=n;const src=a.createBufferSource();src.buffer=n;src.loop=true;const filter=a.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1300;const gain=a.createGain();gain.gain.value=.12;src.connect(filter);filter.connect(gain);gain.connect(this.master);src.start()}catch(e){this.ctx=null}}
 setVolume(v){this.volume=v;if(this.ctx)this.master.gain.setTargetAtTime(v*.4,this.ctx.currentTime,.1)}
 tone(freq,duration=.6,vol=.12,type='sine',delay=0){if(!this.ctx||!this.volume||vol<=0)return;const a=this.ctx,t=a.currentTime+delay,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02)}
 chime(){[587.33,880,1174.66].forEach((f,i)=>this.tone(f,1.5,.09,'sine',i*.17))}
 foot(sprint,map){if(!this.ctx)return;const a=this.ctx,o=a.createBufferSource(),g=a.createGain(),f=a.createBiquadFilter();o.buffer=this.noise;f.type='bandpass';f.frequency.value=map==='shrine'?520:map==='river'?850:1250;f.Q.value=.8;g.gain.setValueAtTime(sprint?.85:.45,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.09);o.connect(f);f.connect(g);g.connect(this.master);o.start();o.stop(a.currentTime+.1)}
 tick(t,fear,mode,map){if(!this.ctx)return;this.pad.gain.setTargetAtTime(mode==='play'?.1+fear*.06:.07,this.ctx.currentTime,.5);if(t>this.nextNote){this.nextNote=t+5+Math.random()*5;const notes=map==='shrine'?[293.66,349.23,440,523.25]:[220,293.66,329.63,440];this.tone(notes[Math.floor(Math.random()*notes.length)],3,.025)}if(fear>.15&&t>this.heartTime){this.heartTime=t+1.2-fear*.65;this.tone(52,.15,.12);this.tone(47,.14,.07,'sine',.16)}}
 }
 const G={s:fresh(),mode:'title',camera:{x:0,y:0},enemies:[],keys:new Set(),particles:[],walkPhase:0,hiding:false,fear:0,stamina:1,nearest:null,fade:0,clock:0,grace:3,transitionLock:0,dialog:null,chapterTimer:0,toastTimer:0,subtitleTimer:0,saveTimer:0,settings:{volume:.45,brightness:.62,rain:true,easy:false,textSpeed:35,touch:matchMedia('(pointer:coarse)').matches,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches},audio:new Sound(),endingIds:[],
 blocked(x,y,r=6){const m=H.maps[this.s.map];for(const [a,b]of [[x-r,y-r],[x+r,y-r],[x-r,y+r],[x+r,y+r]]){let tx=Math.floor(a/32),ty=Math.floor(b/32);if(tx<0||ty<0||tx>=m.w||ty>=m.h||m.tiles[ty][tx]===3||m.tiles[ty][tx]===4)return true}for(const o of m.objects){const b=o.solid;if(b&&x+r>b.x&&x-r<b.x+b.w&&y+r>b.y&&y-r<b.y+b.h)return true}return false},
 safePosition(){if(!this.blocked(this.s.x,this.s.y))return;const x=this.s.x,y=this.s.y;for(let rad=16;rad<1500;rad+=16)for(let a=0;a<Math.PI*2;a+=Math.PI/8){const xx=x+Math.cos(a)*rad,yy=y+Math.sin(a)*rad;if(!this.blocked(xx,yy)){this.s.x=xx;this.s.y=yy;return}}},
 setupMap(snap=true){const m=H.maps[this.s.map];this.enemies=m.enemies.map((e,i)=>({...JSON.parse(JSON.stringify(e)),origin:{x:e.x,y:e.y},index:0,alert:0,banish:0,hidden:false,cool:0,fade:1,seed:i}));this.particles=[];this.nearest=null;this.fear=0;this.grace=4;this.safePosition();if(snap){this.camera.x=clamp(this.s.x-H.W/2,0,m.w*32-H.W);this.camera.y=clamp(this.s.y-H.H/2,0,m.h*32-H.H)}this.updateHUD()},
 updateHUD(){const s=this.s;$('chapter').textContent=['序章','第一章','第二章','第三章','終章'][s.chapter];$('place').textContent=H.maps[s.map].name;$('objective').textContent=H.objective(s);$('lampStatus').textContent=s.light?'灯り':'消灯';document.querySelector('.status').classList.toggle('off',!s.light);$('stamina').style.width=this.stamina*100+'%';$('touch').hidden=!this.settings.touch||this.mode!=='play'},
 showTitle(){this.sessionActive=false;this.menuFromTitle=false;this.mode='title';this.keys.clear();$('hud').hidden=true;$('dialog').hidden=true;$('chapterCard').hidden=true;$('touch').hidden=true;this.chapterTimer=0;this.s=fresh();this.s.x=790;this.s.y=575;this.s.dir={x:.8,y:.6};this.setupMap();let can=!!this.readSlot('auto');$('overlay').innerHTML=`<section class="title-screen"><div class="eyebrow">夜道探索ホラー · オリジナル短編</div><h1>灯返り<small>H I G A E R I</small></h1><p class="tagline">名前のない夏祭り<br>むかえにきたのは、だれだった。</p><nav class="title-menu"><button id="newGame">はじめから</button><button id="continueGame" ${can?'':'disabled'}>つづきから</button><button id="loadGame">記録をひらく</button><button id="titleSettings">設定・遊びかた</button></nav><div class="edition">HEADPHONES RECOMMENDED　 /　 4 AREAS · 3 ENDINGS</div></section>`;$('newGame').onclick=()=>{this.audio.init();if(this.readSlot('auto'))this.confirmNew();else this.newGame()};$('continueGame').onclick=()=>this.loadSlot('auto');$('loadGame').onclick=()=>this.loadMenu(true);$('titleSettings').onclick=()=>this.settingsMenu(true)},
 confirmNew(){this.panel('新しい夜を始める','<p>オートセーブを新しい物語で上書きします。手動の記録は残ります。</p><div class="row"><button id="yesNew">はじめから</button><button id="cancelNew">戻る</button></div>');$('yesNew').onclick=()=>this.newGame();$('cancelNew').onclick=()=>this.showTitle()},
 newGame(){this.sessionActive=true;this.menuFromTitle=false;this.s=fresh();this.stamina=1;this.audio.init();this.audio.setVolume(this.settings.volume);this.mode='play';$('overlay').innerHTML='';$('hud').hidden=false;this.setupMap();this.saveAuto();H.intro(this)},
 resume(){this.mode='play';this.keys.clear();$('overlay').innerHTML='';$('hud').hidden=false;this.grace=Math.max(this.grace,1);this.updateHUD()},
 pause(){if(this.mode!=='play')return;this.mode='menu';this.keys.clear();this.pauseMenu()},
 panel(title,html,wide=false){$('dialog').hidden=true;$('touch').hidden=true;this.keys.clear();$('overlay').innerHTML=`<div class="menu-backdrop"><section class="panel ${wide?'wide':''}" role="dialog" aria-label="${esc(title)}"><h2>${esc(title)}</h2>${html}</section></div>`},
 pauseMenu(){this.menuFromTitle=false;this.mode='menu';this.panel('夜の途中で',`<p>${esc(H.maps[this.s.map].name)}<br>${esc(H.objective(this.s))}</p><div class="row"><button id="resume">探索を続ける</button><button id="journal">手帳</button><button id="map">地図</button></div><div class="row"><button id="load">記録を読む</button><button id="export">記録を書き出す</button><button id="settings">設定</button><button id="title">表紙へ</button></div><p class="muted">物語の節目に自動記録。お地蔵さまで手動記録できます。</p>`);$('resume').onclick=()=>this.resume();$('journal').onclick=()=>this.journal();$('map').onclick=()=>this.mapMenu();$('load').onclick=()=>this.loadMenu(false);$('export').onclick=()=>this.exportSave();$('settings').onclick=()=>this.settingsMenu(false);$('title').onclick=()=>{this.saveAuto();this.showTitle()}},
 say(lines,after){this.mode='dialog';this.keys.clear();$('overlay').innerHTML='';$('dialog').hidden=false;$('choices').innerHTML='';$('nextDialog').hidden=false;this.dialog={lines:lines.map(v=>typeof v==='string'?{s:'',t:v}:v),index:0,count:0,after};this.showLine();this.updateHUD()},
 showLine(){const d=this.dialog;if(!d)return;d.count=0;const v=d.lines[d.index];$('speaker').textContent=v.s||'　';$('dialogText').textContent=this.settings.textSpeed===0?v.t:''},
 advance(){if(this.mode!=='dialog'||!this.dialog)return;let d=this.dialog,v=d.lines[d.index];if(d.count<v.t.length&&this.settings.textSpeed!==0){d.count=v.t.length;$('dialogText').textContent=v.t;return}d.index++;if(d.index>=d.lines.length){const cb=d.after;this.dialog=null;$('dialog').hidden=true;this.mode='play';this.updateHUD();if(cb)cb()}else this.showLine()},
 choose(prompt,choices){this.mode='choice';this.keys.clear();this.dialog=null;$('dialog').hidden=false;$('speaker').textContent='　';$('dialogText').textContent=prompt;$('nextDialog').hidden=true;$('choices').innerHTML='';choices.forEach((o,i)=>{const b=document.createElement('button');b.textContent=o.text;b.onclick=()=>{this.mode='play';$('dialog').hidden=true;$('choices').innerHTML='';o.action()};$('choices').appendChild(b)});$('choices').firstElementChild?.focus();this.updateHUD()},
 interact(){if(this.mode==='dialog'){this.advance();return}if(this.mode!=='play'||this.chapterTimer>0)return;if(this.nearest)H.interact(this,this.nearest)},
 toggleLight(){if(this.mode!=='play')return;this.s.light=!this.s.light;this.audio.tone(this.s.light?450:210,.05,.035,'triangle');this.updateHUD()},
 toast(text){$('toast').textContent=text;$('toast').style.opacity='1';this.toastTimer=4},
 subtitle(text){$('subtitle').textContent=text;$('subtitle').style.opacity='1';this.subtitleTimer=5},
 chapter(n){this.s.chapter=n;this.chapterTimer=3.4;$('cardNum').textContent=['序章','第一章','第二章','第三章','終章'][n];$('cardTitle').textContent=H.chapters[n].title;$('cardSub').textContent=H.chapters[n].sub;$('chapterCard').hidden=false;this.keys.clear();this.audio.chime();this.updateHUD();this.saveAuto()},
 lore(id){if(!this.s.lore.includes(id)){this.s.lore.push(id);this.toast('手帳に「'+H.lore[id].name+'」の作法を書いた');this.saveAuto()}},
 record(){return {...JSON.parse(JSON.stringify(this.s)),savedAt:new Date().toISOString()}},
 saveAuto(){if(!this.sessionActive)return false;const ok=storage.set('auto',JSON.stringify(this.record()));this.saveTimer=0;if(!ok&&!this.warnedStorage){this.warnedStorage=true;this.toast('ブラウザ保存が使えません。メニューから記録を書き出してください。')}return ok},
 readSlot(slot){try{let raw=JSON.parse(storage.get(slot));if(!raw)return null;const s=validate(raw);return {...s,savedAt:raw.savedAt}}catch(e){return null}},
 slotLabel(slot){const s=this.readSlot(slot);if(!s)return '記録なし';const d=new Date(s.savedAt);return `${H.maps[s.map].name} · 記憶 ${s.memories.length}/7 · ${Math.floor(s.seconds/60)}分${isNaN(d)?'':' · '+d.toLocaleDateString('ja-JP')+' '+d.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}`},
 saveMenu(){this.mode='menu';this.panel('灯りのそばで記録する',`<p class="muted">同じ欄への記録は上書きされます。オートセーブは別に残ります。</p>${[1,2,3].map(i=>`<button class="save-slot" id="save${i}"><span>記録 ${i}</span><span>${esc(this.slotLabel('slot'+i))}</span></button>`).join('')}<div class="row"><button id="saveBack">探索へ戻る</button><button id="saveExport">記録を書き出す</button></div>`);[1,2,3].forEach(i=>$('save'+i).onclick=()=>{const ok=storage.set('slot'+i,JSON.stringify(this.record()));this.audio.chime();this.toast(ok?'記録 '+i+' に保存しました':'保存できません。記録を書き出してください。');this.saveMenu()});$('saveBack').onclick=()=>this.resume();$('saveExport').onclick=()=>this.exportSave()},
 loadMenu(fromTitle){this.mode='menu';this.menuFromTitle=fromTitle;this.panel('残された記録',`${['auto','slot1','slot2','slot3'].map((slot,i)=>`<button class="save-slot" id="load${i}" ${this.readSlot(slot)?'':'disabled'}><span>${i?'記録 '+i:'自動記録'}</span><span>${esc(this.slotLabel(slot))}</span></button>`).join('')}<div class="row"><button id="import">ファイルから読み込む</button><button id="loadBack">戻る</button></div><p class="muted">保存はこのブラウザ内です。別の場所で遊ぶときは「記録を書き出す」を使ってください。</p>`);['auto','slot1','slot2','slot3'].forEach((slot,i)=>$('load'+i).onclick=()=>this.loadSlot(slot));$('loadBack').onclick=()=>fromTitle?this.showTitle():this.pauseMenu();$('import').onclick=()=>$('importSave').click()},
 loadSlot(slot){let s=this.readSlot(slot);if(!s){this.toast('記録を読み込めませんでした。');return}this.loadState(s)},
 loadState(s){this.sessionActive=true;this.menuFromTitle=false;this.s=validate(s);this.audio.init();this.audio.setVolume(this.settings.volume);this.stamina=1;this.mode='play';$('chapterCard').hidden=true;this.chapterTimer=0;$('dialog').hidden=true;this.dialog=null;this.setupMap();this.resume();this.transitionLock=2;this.toast('記録から、夜を再開しました');if(!this.s.flags.letter)H.intro(this)},
 exportSave(){const data=JSON.stringify(this.record(),null,2),url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='灯返り-記録-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);this.toast('記録ファイルを書き出しました')},
 journal(){if(this.mode==='dialog'||this.mode==='choice')return;this.mode='menu';let s=this.s;this.panel('夜道の手帳',`<p class="muted">${s.memories.length} / 7 の記憶　 ·　 ${Math.floor(s.seconds/60)} 分の夜</p><div class="journal-grid"><div><div class="journal-entry"><h3>いま、すること</h3><p>${esc(H.objective(s))}</p></div><h3 class="eyebrow">持ちもの</h3>${s.items.map(k=>`<div class="journal-entry"><h3>${H.items[k].name}</h3><p>${H.items[k].desc}</p></div>`).join('')||'<p>まだ、何もない。</p>'}<h3 class="eyebrow">夜道の作法</h3>${s.lore.map(k=>`<div class="journal-entry"><h3>${H.lore[k].name}</h3><p>${H.lore[k].text}</p></div>`).join('')||'<p>町の掲示板を確かめよう。</p>'}</div><div><h3 class="eyebrow">紬のこと</h3>${Object.keys(H.memories).map((k,i)=>s.memories.includes(k)?`<div class="journal-entry"><h3>${H.memories[k].title}</h3><p>${esc(H.memories[k].text).replace(/\n/g,'<br>')}</p></div>`:`<div class="journal-entry"><h3>0${i+1} / まだ思い出せない</h3><p>町のどこかに、小さな時間が残っている。</p></div>`).join('')}</div></div><div class="row"><button id="journalBack">探索へ戻る</button><button id="journalMap">地図を見る</button></div>`,true);$('journalBack').onclick=()=>this.resume();$('journalMap').onclick=()=>this.mapMenu()},
 mapMenu(){if(this.mode==='dialog'||this.mode==='choice')return;this.mode='menu';const names={home:'東 → 宵待ち商店街<br>北 → 忘れ川（鏡を入手後）',market:'西 → 住宅街<br>東 → 忘れ川（鏡を入手後）',river:'西 → 商店街<br>南西 → 住宅街<br>東 → 灯守神社（糸を入手後）',shrine:'西 → 忘れ川'};const objects=H.maps[this.s.map].objects.filter(o=>o.interact&&(H.memories[o.id]||!['door','sister'].includes(o.type)));this.panel('紬の帰り道',`<div class="map-wrap"><canvas id="mapCanvas" aria-label="現在地と調べられる場所の地図"></canvas><div class="map-legend"><b>${H.maps[this.s.map].name}</b><br><span style="color:#f08b79">● 現在地</span>　<span style="color:#dbad6a">● 地蔵</span><br><span style="color:#a9cace">● まだ見つけていない記憶</span><br><br>${names[this.s.map]}<br><br>${objects.map((o,i)=>{const done=this.s.memories.includes(o.id);return `<span style="color:${done?'#74857e':'#c7c5ac'}">${done?'✓ ':''}${i+1}. ${esc(o.label)} <small>(${Math.round(o.x/32)}, ${Math.round(o.y/32)})</small></span>`}).join('<br>')}<br><small>座標は左上から。1目盛り = 1区画。</small></div></div><div class="row"><button id="mapBack">探索へ戻る</button><button id="mapJournal">手帳を見る</button></div>`,true);H.drawMap($('mapCanvas'),this);$('mapBack').onclick=()=>this.resume();$('mapJournal').onclick=()=>this.journal()},
 settingsMenu(fromTitle){this.mode='menu';this.menuFromTitle=fromTitle;this.panel('設定・遊びかた',`<label>音量<input id="volume" type="range" min="0" max="100" value="${this.settings.volume*100}"></label><label>画面の明るさ<input id="brightness" type="range" min="45" max="85" value="${Math.round((1.3-this.settings.brightness)*100)}"></label><label>文字の速さ<select id="textSpeed"><option value="20">ゆっくり</option><option value="35">ふつう</option><option value="60">速い</option><option value="0">一括表示</option></select></label><label>物語を優先（妖怪に捕まらない）<input type="checkbox" id="easy" ${this.settings.easy?'checked':''}></label><label>雨の表示<input type="checkbox" id="rain" ${this.settings.rain?'checked':''}></label><label>画面の操作ボタン<input type="checkbox" id="touchSetting" ${this.settings.touch?'checked':''}></label><p>移動：WASD / 矢印　走る：Shift　調べる：E / Enter<br>灯り：F　隠れる：草地で Ctrl 長押し　灯りの向き：マウス<br>手帳：J　地図：M　中断：Esc　全画面：Alt + Enter<br>会話中の E は全文表示 → 次の台詞。選択肢はクリック、または Tab と Enter。</p><p class="muted">妖怪に捕まっても品や記憶は失いません。最後のお地蔵さまへ戻ります。<br>点滅する驚かせ演出は使っていません。端末を離れると自動的に中断します。</p><div class="row"><button id="settingsBack">戻る</button><button id="fullscreen">全画面</button></div>`,true);$('textSpeed').value=String(this.settings.textSpeed);const persist=()=>storage.set('settings',JSON.stringify(this.settings));$('volume').oninput=e=>{this.settings.volume=Number(e.target.value)/100;this.audio.init();this.audio.setVolume(this.settings.volume);persist()};$('brightness').oninput=e=>{this.settings.brightness=1.3-Number(e.target.value)/100;persist()};$('textSpeed').onchange=e=>{this.settings.textSpeed=Number(e.target.value);persist()};['easy','rain'].forEach(k=>$(k).onchange=e=>{this.settings[k]=e.target.checked;persist()});$('touchSetting').onchange=e=>{this.settings.touch=e.target.checked;persist()};$('settingsBack').onclick=()=>fromTitle?this.showTitle():this.pauseMenu();$('fullscreen').onclick=()=>this.fullscreen()},
 fullscreen(){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else $('game').requestFullscreen?.().catch(()=>this.toast('この画面では全画面表示を使えません。'))},
 end(id){this.saveAuto();const e=H.endings[id];this.say(e.lines,()=>{this.mode='ending';$('hud').hidden=true;if(!this.endingIds.includes(id)){this.endingIds.push(id);storage.set('endings',JSON.stringify(this.endingIds))}$('overlay').innerHTML=`<section class="ending"><div class="eyebrow">${e.no}　 /　 灯返り</div><h1>${e.title}</h1><p>${esc(e.text).replace(/\n/g,'<br>')}</p><p class="eyebrow">記憶 ${this.s.memories.length} / 7　 ·　 見つけた結末 ${this.endingIds.length} / 3</p><button id="endingBack">選ぶ前に戻る</button><button id="endingTitle">表紙へ</button><p class="muted" style="font-size:11px">おしまい。夜を歩いてくれて、ありがとう。<br>物語・図像・音楽は本作のためのオリジナルです。</p></section>`;$('endingBack').onclick=()=>{this.resume();this.toast('町の記憶を探し直すこともできます')};$('endingTitle').onclick=()=>this.showTitle();this.audio.chime()})},
 caught(){if(this.settings.easy||this.grace>0)return;this.mode='caught';this.keys.clear();this.fade=1;this.audio.tone(65,.9,.16);this.say([{s:'',t:'数えそこねた足音が、すぐ後ろで止まった。\n気づくと、灯りのそばに座っていた。'},{s:'澪',t:'……大丈夫。覚えている。\n手帳も、持ちものも、ここにある。'}],()=>{const cp=this.s.checkpoint;this.s.map=cp.map;this.s.x=cp.x;this.s.y=cp.y;this.s.light=true;this.setupMap();this.grace=7;this.fear=0;this.stamina=1;this.saveAuto();this.toast('品や記憶は失われていません。作法は J で確認できます。')})},
 moveMap(e){if(e.requires&&!this.s.flags[e.requires]){this.transitionLock=1.8;this.toast(e.requires==='bell'?'商店街への道が見えない。まず、手紙と電話を確かめよう。':e.requires==='mirror'?'道が夜に溶けている。お面屋で鏡を受け取ろう。':'鳥居への道には、川で見つける「約束の糸」が必要だ。');return}this.s.map=e.to;this.s.x=e.tx;this.s.y=e.ty;this.transitionLock=2;this.fade=1;this.setupMap();const j=H.maps[e.to].objects.find(o=>o.type==='jizo');if(j)this.s.checkpoint={map:e.to,x:j.x+22,y:j.y+14};this.saveAuto();this.subtitle(H.maps[e.to].name);if(e.to==='market'){this.lore('umbrella');this.lore('parade')}if(e.to==='river')this.lore('longneck')},
 update(dt){this.clock+=dt;if(this.sessionActive&&['play','dialog','choice'].includes(this.mode))this.s.seconds+=dt;this.toastTimer-=dt;if(this.toastTimer<=0)$('toast').style.opacity='0';this.subtitleTimer-=dt;if(this.subtitleTimer<=0)$('subtitle').style.opacity='0';this.fade=Math.max(0,this.fade-dt*.6);this.audio.tick(this.clock,this.fear,this.mode,this.s.map);if(this.mode==='play'&&this.s.map==='home'&&this.s.flags.letter&&!this.s.flags.bell&&this.clock>(this.ringTime||0)){this.ringTime=this.clock+4.8;const v=clamp(1-Math.hypot(this.s.x-992,this.s.y-512)/650,0,1)*.12;[0,.14,.28,.6,.74,.88].forEach(d=>this.audio.tone(780,.1,v,'sine',d));}
 if(this.mode==='dialog'&&this.dialog){const d=this.dialog,v=d.lines[d.index];d.count=this.settings.textSpeed===0?v.t.length:Math.min(v.t.length,d.count+dt*this.settings.textSpeed);$('dialogText').textContent=v.t.slice(0,Math.floor(d.count))}
 if(this.chapterTimer>0){this.chapterTimer-=dt;if(this.chapterTimer<=0)$('chapterCard').hidden=true;return}
 if(this.mode!=='play')return;this.grace=Math.max(0,this.grace-dt);this.transitionLock=Math.max(0,this.transitionLock-dt);this.saveTimer+=dt;if(this.saveTimer>30&&this.fear<.1)this.saveAuto();
 const s=this.s,m=H.maps[s.map],k=this.keys;let dx=(k.has('d')||k.has('ArrowRight')?1:0)-(k.has('a')||k.has('ArrowLeft')?1:0),dy=(k.has('s')||k.has('ArrowDown')?1:0)-(k.has('w')||k.has('ArrowUp')?1:0),moving=!!(dx||dy);const tile=m.tiles[Math.floor(s.y/32)]?.[Math.floor(s.x/32)];this.hiding=k.has('Control')&&tile===0;const crouch=k.has('Control'),sprint=k.has('Shift')&&moving&&!crouch&&this.stamina>.04;this.stamina=clamp(this.stamina+dt*(sprint?-.23:.16),0,1);if(moving){const n=Math.hypot(dx,dy);dx/=n;dy/=n;if(this.clock-(this.aimTime||0)>.65)s.dir={x:dx,y:dy};const speed=crouch?40:sprint?142:83;let nx=s.x+dx*speed*dt,ny=s.y+dy*speed*dt;if(!this.blocked(nx,s.y))s.x=nx;if(!this.blocked(s.x,ny))s.y=ny;this.walkPhase+=dt*(sprint?16:9);if(!crouch&&this.clock>this.audio.stepTime){this.audio.foot(sprint,s.map);this.audio.stepTime=this.clock+(sprint?.23:.37);this.particles.push({x:s.x+(Math.sin(this.walkPhase)>0?-4:4),y:s.y+2,life:.6,color:'#adbdba'})}}else this.walkPhase=0;
 this.particles.forEach(p=>p.life-=dt*.5);this.particles=this.particles.filter(p=>p.life>0);this.nearest=null;let min=46;for(const o of m.objects){if(!o.interact)continue;const d=dist(s,o);if(d<min){min=d;this.nearest=o}}
 $('prompt').textContent=this.nearest?'[ E ]　'+this.nearest.label:this.hiding?'草陰で、息をひそめている':'';
 let danger=0;const safe=m.objects.some(o=>o.type==='jizo'&&dist(s,o)<90);for(const e of this.enemies){if(e.type==='listener'&&!s.flags.letter)continue;e.cool=Math.max(0,e.cool-dt);if(e.banish>0){e.banish-=dt;e.hidden=true;if(e.banish<=0){e.x=e.origin.x;e.y=e.origin.y;e.hidden=false;e.fade=0}continue}e.fade=Math.min(1,e.fade+dt*.4);let d=dist(s,e),target=e.route[e.index],spd=e.type==='parade'?23:e.type==='umbrella'?26:e.type==='listener'?22:8;const aimDot=((e.x-s.x)*s.dir.x+(e.y-s.y)*s.dir.y)/Math.max(1,d);const facing=s.light&&aimDot>.72&&d<215;
 let detected=false;if(e.type==='listener')detected=!this.hiding&&!crouch&&moving&&d<(sprint?230:70);if(e.type==='umbrella')detected=s.light&&d<160&&(facing||d<58);if(e.type==='longneck'){if(d<175&&!moving&&facing){e.calm=(e.calm||0)+dt;if(e.calm>2.6){e.banish=12;e.calm=0;this.subtitle('数える声が、水の下に沈んだ。');continue}}else e.calm=Math.max(0,(e.calm||0)-dt*.3);detected=moving&&d<140;}
 if(safe||this.hiding||this.grace>0)detected=false;if(e.type==='umbrella'&&!s.light)e.alert=0;if(detected){e.alert=3;this.lore(e.type)}else e.alert=Math.max(0,e.alert-dt*(safe?3:1));if(e.alert>0&&!safe&&!this.hiding&&e.type!=='parade'){target=s;spd=e.type==='longneck'?46:e.type==='umbrella'?98:112}else if(dist(e,target)<10)e.index=(e.index+1)%e.route.length;
 if(e.type==='longneck'&&(e.calm||0)>0&&!moving)spd=0;const n=Math.hypot(target.x-e.x,target.y-e.y);if(n>2){let ex=e.x+(target.x-e.x)/n*spd*dt,ey=e.y+(target.y-e.y)/n*spd*dt;if(e.type==='longneck'){e.x=clamp(ex,22.5*32,28.5*32);e.y=clamp(ey,17.3*32,20.6*32)}else{if(!this.blocked(ex,e.y,5))e.x=ex;if(!this.blocked(e.x,ey,5))e.y=ey}}
 d=dist(s,e);if(!safe&&!this.hiding&&this.grace<=0){let ed=e.type==='parade'?Math.min(d,...[1,2,3].map(i=>Math.hypot(s.x-e.x-i*18,s.y-e.y))):d;danger=Math.max(danger,clamp(1-ed/125,0,1)*(e.alert>0?1:.55));if(ed<(e.type==='longneck'?17:15)&&e.cool<=0){if(!this.settings.easy){this.caught();return}else e.cool=3}}}
 this.fear+=(danger-this.fear)*Math.min(1,dt*3);if(this.fear>.5&&this.clock>(this.hintTime||0)){this.hintTime=this.clock+14;this.subtitle('足音が、ひとつ多い。')}
 for(const e of m.exits){if(this.transitionLock<=0&&s.x>=e.x&&s.x<=e.x+e.w&&s.y>=e.y&&s.y<=e.y+e.h){this.moveMap(e);break}}const map=H.maps[s.map];const ease=this.settings.reduced?1:Math.min(1,dt*6);this.camera.x+=(clamp(s.x-H.W/2,0,map.w*32-H.W)-this.camera.x)*ease;this.camera.y+=(clamp(s.y-H.H/2,0,map.h*32-H.H)-this.camera.y)*ease;this.updateHUD();
 }
 };
 try{let st=JSON.parse(storage.get('settings'));if(st){if(Number.isFinite(st.volume))G.settings.volume=clamp(st.volume,0,1);if(Number.isFinite(st.brightness))G.settings.brightness=clamp(st.brightness,.45,.85);for(const k of ['rain','easy','touch'])if(typeof st[k]==='boolean')G.settings[k]=st[k];if([0,20,35,60].includes(st.textSpeed))G.settings.textSpeed=st.textSpeed}let ends=JSON.parse(storage.get('endings'));if(Array.isArray(ends))G.endingIds=ends.filter(e=>Object.hasOwn(H.endings,e))}catch(e){}
 G.audio.volume=G.settings.volume;G.showTitle();H.game=G;H.validate=validate;
 $('nextDialog').onclick=()=>G.advance();$('menuBtn').onclick=()=>G.pause();
 window.addEventListener('keydown',e=>{const tag=e.target.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag))return;if(e.altKey&&e.key==='Enter'){e.preventDefault();G.fullscreen();return}const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Control','Tab'].includes(k)&&G.mode==='play')e.preventDefault();if(e.repeat)return;G.audio.init();G.keys.add(k);if(k==='Escape'){if(G.mode==='play')G.pause();else if(G.mode==='menu'){if(G.menuFromTitle){G.menuFromTitle=false;G.showTitle()}else G.resume()}return}if((k==='e'||k==='Enter'||k===' ')&&(G.mode==='play'||G.mode==='dialog')){e.preventDefault();G.interact()}if(G.mode==='play'){if(k==='f')G.toggleLight();if(k==='j')G.journal();if(k==='m')G.mapMenu()}else if(G.mode==='menu'&&(k==='j'||k==='m')&&!G.menuFromTitle)G.resume()});
 window.addEventListener('keyup',e=>G.keys.delete(e.key.length===1?e.key.toLowerCase():e.key));
 $('screen').addEventListener('pointermove',e=>{if(G.mode!=='play'||e.pointerType==='touch')return;const r=$('screen').getBoundingClientRect(),x=(e.clientX-r.left)*H.W/r.width+G.camera.x-G.s.x,y=(e.clientY-r.top)*H.H/r.height+G.camera.y-G.s.y+13,n=Math.hypot(x,y);if(n>10){G.s.dir={x:x/n,y:y/n};G.aimTime=G.clock}});
 $('screen').addEventListener('pointerdown',()=>{G.audio.init()});
 document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);G.audio.init();G.keys.add(b.dataset.key)};b.onpointerup=b.onpointercancel=()=>G.keys.delete(b.dataset.key);b.onlostpointercapture=()=>G.keys.delete(b.dataset.key)});
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{G.audio.init();({light:()=>G.toggleLight(),interact:()=>G.interact(),journal:()=>G.journal(),map:()=>G.mapMenu()})[b.dataset.action]()});
 window.addEventListener('blur',()=>{G.keys.clear();if(G.mode==='play')G.pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){G.keys.clear();if(G.mode==='play')G.pause();if(G.mode!=='title')G.saveAuto()}});window.addEventListener('beforeunload',()=>{if(G.mode!=='title')G.saveAuto()});
 $('importSave').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>100000)throw Error('ファイルが大きすぎます。');const raw=JSON.parse(await file.text()),s=validate(raw);G.panel('記録を読み込みますか',`<p>${esc(H.maps[s.map].name)} · 記憶 ${s.memories.length} / 7<br>現在の探索を、この記録から再開します。</p><div class="row"><button id="confirmImport">この記録から再開</button><button id="cancelImport">戻る</button></div>`);$('confirmImport').onclick=()=>{G.loadState(s);G.saveAuto()};$('cancelImport').onclick=()=>G.loadMenu(G.menuFromTitle)}catch(err){G.toast('読み込めません：'+err.message)}};
 let last=performance.now();function frame(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;G.update(dt);H.render(G,G.clock);requestAnimationFrame(frame)}requestAnimationFrame(frame);
})(HG);
